#!/usr/bin/env node
/**
 * Generates public/sw.js from scripts/sw-template.js, injecting the runtime
 * base path and a version string so the service worker's cache is busted on
 * every new deployment.
 *
 * Runs before `next build` (see the "prebuild" npm script). The generated
 * public/sw.js is then copied into the static export output automatically.
 *
 * Env:
 *   NEXT_PUBLIC_BASE_PATH  - base path the app is served from (e.g. /sudoku).
 *   NEXT_PUBLIC_BUILD_ID   - unique build id (git SHA in CI). Falls back to a
 *                            timestamp for local builds.
 */
const fs = require("fs");
const path = require("path");

const basePath = process.env.NEXT_PUBLIC_BASE_PATH || "";
const version = process.env.NEXT_PUBLIC_BUILD_ID || `dev-${Date.now()}`;

const templatePath = path.join(__dirname, "sw-template.js");
const outputPath = path.join(__dirname, "..", "public", "sw.js");

const template = fs.readFileSync(templatePath, "utf8");

const output =
  `// AUTO-GENERATED by scripts/generate-sw.js. Do not edit directly.\n` +
  `// Edit scripts/sw-template.js instead.\n` +
  template
    .replace(/__VERSION__/g, version)
    .replace(/__BASE_PATH__/g, basePath);

fs.writeFileSync(outputPath, output);

console.log(
  `[generate-sw] wrote public/sw.js (version=${version}, basePath="${basePath}")`
);
